name: Deploy to AWS

on:
  push:
    branches: [main]  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Or another appropriate runner

    steps:
      - uses: Checkout
      - uses: actions/checkout@v3  # Checkout your code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your project's dependencies

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Replace with your AWS access key ID secret
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Replace with your AWS secret access key secret
          aws-region: us-east-1  # Replace with your AWS region secret

      - name: Deploy to AWS 
        run: aws s3 sync . s3://demo-automation-2025 --delete

      - name: Print Groq API Key (for debugging)
        run: echo "${{ secrets.GROQ_API_KEY }}" # For debugging ONLY, REMOVE in production!